import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";

import type { Metadata } from "next";
import type { ReactNode } from "react";

import "@/styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Complete Sign In/Up Form"
};

type RootLayoutProps = {
  children: ReactNode;
};

const RootLayout = ({ children }: RootLayoutProps) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="h-screen flex flex-col justify-center items-center">
          <Navbar />

          {children}
        </main>
      </body>
    </html>
  );
};

export default RootLayout;
